config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :quotations
  resources :users
  resources :profiles
  root to: 'welcome#index'
  
  namespace :api, defaults: {format: 'json'} do 
    namespace :v1 do
      resources :quotations
      get "new_quotation", to: "quotations#new_quotation", as: :new_quotation
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        sessions: 'api/v1/auth/sessions'
      }
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include DeviseTokenAuth::Concerns::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :quotations
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @total_seller = @user.quotations.sum(:value) || 0
    value = NegociationValue.where('min_value <= ?', @total_seller).where('max_value >= ?', @total_seller).first&.comission || 0
    @total = @total_seller * (value / 100)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: quotation) do |form| %>
  <% if quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
        <% quotation.errors.each do |error| %>
          <li><%= quotation.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :form_payment %>
    <%= form.text_field :form_payment %>
  </div>

  <div class="field">
    <%= form.label :installments %>
    <%= form.text_field :installments %>
  </div>

  <div class="field">
    <%= form.label :net_value %>
    <%= form.text_field :net_value %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.number_field :discount %>
  </div>

  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Espelho de Vendas</h1>

<table>
  <thead>
    <tr>
      <th>Vendedor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.email %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Seller Commission</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.quotations.each do |quotation| %>
      <tr>
        <td><%= quotation.name %></td>
        <td><%= quotation.value %></td>
        <td><%= quotation.seller_commission %></td>
        <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
        <td><%= link_to 'Destroy', quotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h1>Acumulado de Vendas</h1>
<%= number_to_currency(@total_seller) %>

<h1>Total Comissão</h1>
<%= number_to_currency(@total) %>

<br>

<%= link_to 'Back', users_path %>