config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :quotations
  resources :users
  resources :profiles
  root to: 'welcome#index'
  
  namespace :api, defaults: {format: 'json'} do 
    namespace :v1 do
      resources :quotations
      get "new_quotation", to: "quotations#new_quotation", as: :new_quotation
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        sessions: 'api/v1/auth/sessions'
      }
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/quotation.rb
# frozen_string_literal: true

class Quotation < ApplicationRecord
  belongs_to :user, optional: true

  # validate_presence_of :value, :installment, :form_payment

  # Callbacks
  before_save :calculate_factory_cost
  before_save :minimal_sale_value
  before_save :calculate_value_with_discount
  before_save :calculate_commissions
  before_save :calculate_other_values
  before_save :calculate_taxs
  before_save :seller_commission
  before_save :result
  before_save :minimal_percent

  def calculate_factory_cost
    self.factory_cost = suggested_price_manufactures * Setup.first.cost_index / 100
  end

  def minimal_sale_value
    if suggested_price_manufactures <= 50000
      self.minimal_sale_value = suggested_price_manufactures * 0.59595
    elsif suggested_price_manufactures <= 80000
      self.minimal_sale_value = suggested_price_manufactures * 0.60714
    elsif suggested_price_manufactures <= 120000
      self.minimal_sale_value = suggested_price_manufactures * 0.61876
    else suggested_price_manufactures > 120001
      self.minimal_sale_value = suggested_price_manufactures * 0.63083
    end
  end

  # Calcula valor desconto
  def calculate_value_with_discount
    self.value = value - (value * (discount / 100))
  end

  def seller_commission
    if value <= 50000
      self.seller_commission = value * 4 / 100
    elsif value <= 80001
      self.seller_commission = value * 5 / 100
    elsif value <= 120000
      self.seller_commission = value * 6 / 100
    else value > 120001
      self.seller_commission = value * 7 / 100
    end
  end
  
  # commissions
  def calculate_commissions
    self.assembler_commission = value * Setup.first.assembler_commission / 100
    self.manager_commission = value * Setup.first.manager_commission / 100
    if finder_commission == 1
      self.finder_commission = value * Setup.first.finder_commission / 100
    else      
      self.finder_commission == 0
    end
  end

  # other_values = transporte, reserva técnica
  def calculate_other_values
    self.shipping_cost = factory_cost * Setup.first.shipping_cost / 100
    self.reserve_cost = value * Setup.first.reserve_cost / 100
  end

  # tax
  def calculate_taxs
    self.tax = value * Setup.first.tax / 100
    self.credit_card_fee = credit_card_fee
  end
  
  def result
    if value > 1
      self.result = (value - factory_cost - seller_commission - assembler_commission - manager_commission -
                     shipping_cost - credit_card_fee - finder_commission - reserve_cost - tax)
      end    
  end

  def minimal_percent
    if value > 1
     self.minimal_percent = ((result / value) * 100).ceil
    end    
  end

  # def quotation_setup
  #   @setup |= Setup.first
  # end
end

app/controllers/api/v1/quotations_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuotationsController < ApplicationController
      before_action :set_quotation, only: %i[edit update destroy]
      # before_action :authenticate_user!

      def index
        @quotations = Quotation.all

        render status: :ok, json: { quotations: QuotationSerializer.new(@quotations).to_h }
      end

      def new_quotation
        @quotations = Quotation.new(suggested_price_manufactures: params[:value])

        render status: :ok, json: { quotations: QuotationSerializer.new(@quotations).to_h }
      end

      def new
        @quotation = Quotation.new
      end

      def create
        @quotation = Quotation.new(quotation_params)

        if @quotation.save
          render status: :ok, json: { quotations: QuotationSerializer.new(@quotation).to_h }
        else
          render json: @quotation.errors, status: :unprocessable_entity
        end
      end

      def show
        @quotation = Quotation.find(params[:id])
        respond_to do |format|
          format.html
          format.pdf do
            pdf = QuotationPdf.new(@quotation)
            send_data pdf.render, filename: "quotation_#{@quotation.id}.pdf",
                                  type: "application/pdf",
                                  disposition: "inline"
          end
        end
      end

      def edit; end

      def update
        if @quotation.update(quotation_params)
          render status: :ok, json: { quotations: QuotationSerializer.new(@quotation).to_h }
        else
          render json: @quotation.errors, status: :unprocessable_entity
        end
      end

      def destroy
        @quotation.destroy
        render status: :ok, json: { quotations: QuotationSerializer.new(@quotation).to_h }
      end

      private

      def set_quotation
        @quotation = Quotation.find(params[:id])
      end

      def quotation_params
        params.require(:quotation).permit(:name, :value, :installments, :discount, :user_id, :suggested_price_manufactures, :minimal_percent)
      end
    end
  end
end

app/controllers/quotations_controller.rb
# frozen_string_literal: true

class QuotationsController < ApplicationController
  before_action :set_quotation, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    @quotations = Quotation.all
  end

  def new
    @quotation = Quotation.new
  end

  def show
    @quotation = Quotation.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = QuotationPdf.new(@quotation)
        send_data pdf.render, filename: "quotation_#{@quotation.id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def create
    @quotation = Quotation.new(quotation_params)

    if @quotation.save
      redirect_to quotations_path
    else
      render json: @quotation.errors, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if params[:quotation][:value].to_i >= params[:quotation][:minimal_sale_value].to_i
      if @quotation.update(quotation_params)
        redirect_to quotations_path
      else
        render json: @quotation.errors, status: :unprocessable_entity
      end
    else
      render json: 'Não Autorizado', status: :unprocessable_entity
    end
  end

  def destroy
    @quotation.destroy
    redirect_to quotations_path
  end

  private

  def set_quotation
    @quotation = Quotation.find(params[:id])
  end

  def quotation_params
    params.require(:quotation).permit(:user_id, :name, :value, :installments, :discount, :finder_commission, :suggested_price_manufactures, :factory_cost, :credit_card_fee, :result)
  end
end

app/helpers/quotation_helper.rb
module QuotationHelper
end

app/views/quotations/_form.html.erb
<%= form_with(model: quotation) do |form| %>
  <% if quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
        <% quotation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :suggested_price_manufactures %>
    <%= form.text_field :suggested_price_manufactures %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount %>
  </div>

  <div class="field">
    <%= form.label :installments %>
    <%= form.number_field :installments %>
  </div>

  <div class="field">
    <%= form.label :credit_card_fee %>
    <%= form.text_field :credit_card_fee %>
  </div>

  <div class="field">
    <%= form.label :finder_commission %>
    <%= form.text_field :finder_commission %>
  </div>

  <% unless @quotation.new_record? %>
    <div class="field">
      <%= form.label :factory_cost %>
      <%= form.text_field :factory_cost %>
    </div>

    <div class="field">
      <%= form.label :form_payment %>
      <%= form.text_field :form_payment %>
    </div>

    <div class="field">
      <%= form.label :minimal_sale_value %>
      <%= form.text_field :minimal_sale_value %>
    </div>

    <div class="field">
      <%= form.label :reserve_cost %>
      <%= form.text_field :reserve_cost %>
    </div>

    <div class="field">
      <%= form.label :net_value %>
      <%= form.text_field :net_value %>
    </div>

    <div class="field">
      <%= form.label :tax %>
      <%= form.text_field :tax %>
    </div>

    <div class="field">
      <%= form.label :manager_commission %>
      <%= form.text_field :manager_commission %>
    </div>

    <div class="field">
      <%= form.label :assembler_commission %>
      <%= form.text_field :assembler_commission %>
    </div>

    <div class="field">
      <%= form.label :seller_commission %>
      <%= form.text_field :seller_commission %>
    </div>

    <div class="field">
      <%= form.label :shipping_cost %>
      <%= form.text_field :shipping_cost %>
    </div>
  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotations/edit.html.erb
<h2>edit quotation</h2>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Back', quotations_path %>

app/views/quotations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Suggested Price Manufactures</th>
      <th>Factory cost</th>
      <th>Form payment</th>
      <th>Minimal sale value</th>
      <th>Reserve cost</th>
      <th>Credit card fee</th>
      <th>Installments</th>
      <th>minimal_percent</th>
      <th>Discount</th>
      <th>Tax</th>
      <th>Manager commission</th>
      <th>Assembler commission</th>
      <th>Seller commission</th>
      <th>Shipping cost</th>
      <th>Finder Commission</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotations.each do |quotation| %>
      <tr>
        <td><%= quotation.name %></td>
        <td><%= quotation.value %></td>
        <td><%= quotation.suggested_price_manufactures %></td>
        <td><%= quotation.factory_cost %></td>
        <td><%= quotation.form_payment %></td>
        <td><%= quotation.minimal_sale_value %></td>
        <td><%= quotation.reserve_cost %></td>
        <td><%= quotation.credit_card_fee %></td>
        <td><%= quotation.installments %></td>
        <td><%= quotation.minimal_percent %></td>
        <td><%= quotation.discount %></td>
        <td><%= quotation.tax %></td>
        <td><%= quotation.manager_commission %></td>
        <td><%= quotation.assembler_commission %></td>
        <td><%= quotation.seller_commission %></td>
        <td><%= quotation.shipping_cost %></td>
        <td><%= quotation.finder_commission %></td>
        <td><%= link_to 'PDF', quotation_path(quotation.id, format: "pdf") %></td>
        <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
        <td><%= link_to 'Destroy', quotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quotation', new_quotation_path %>

<%= link_to 'Back', root_path %>

app/views/quotations/new.html.erb
<h2>Nova Cotação</h2>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Back', quotations_path %>